name: Docs Versioning
on:
  push:
    tags:
      - 'v?*.*.*'
permissions:
  contents: write
jobs:
  docs:
    name: Generate Website for new version
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Install freeglut
        run: sudo apt-get install -y freeglut3-dev xvfb

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Install Miniworld
        run: pip install .

      - name: Generate Environments page
        run: xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" python docs/_scripts/gen_env_docs.py

      - name: Generate Environments page
        run: xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" python docs/_scripts/gen_envs_display.py

      - name: Build
        run: sphinx-build -b dirhtml -v docs _build

      - name: Move 404
        run: mv _build/404/index.html _build/404.html

      - name: Update 404 links
        run: python docs/_scripts/move_404.py _build/404.html

      - name: Remove .doctrees
        run: rm -r _build/.doctrees

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
          target-folder: ${{steps.tag.outputs.tag}}
          clean: false

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
          clean-exclude: |
            *.*.*/
            main
